name: Google Search Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [Firefox,Chrome]
    env:
      email: ${{ secrets.EMAIL }}
      password: ${{ secrets.PASS }}
    
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
             java-version: '11'
             distribution: 'adopt'
             cache: maven
      - name: Have GitHub Actions Build Maven Project
        run:  mvn -B test site --file pom.xml -DargLine="-DBrowser=${{matrix.browser}}"
      - name: Download report 
        uses: actions/download-artifact@v2
        with:
          path: './target/site'
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: 'Test Report ${{matrix.browser}}'
          path: './target/site' 
          